cloneStaticSiteFromGit:
  enabled: true
  repository: "https://github.com/brunopecampos/kubernetes-node-cassandra"
  branch: "static-frontend"
  interval: 3600
podLabels: { app: frontend }
# Didnt work with git synch
#containerSecurityContext:
#  enabled: true
#  runAsNonRoot: true
#  runAsUser: 1001
