cloneStaticSiteFromGit:
  enabled: true
  repository: "https://github.com/brunopecampos/kubernetes-node-cassandra"
  branch: "static-frontend"
  interval: 3600
podLabels: { app: frontend }
resources:
  limits:
    cpu: "1000m"
    memory: "70Mi"
  requests:
    cpu: "300m"
    memory: "4Mi"
# Didnt work with git synch
#containerSecurityContext:
#  enabled: true
#  runAsNonRoot: true
#  runAsUser: 1001
