version: "3.9"
services:
  rev_proxy:
    build:
      context: "./rev_proxy"
      dockerfile: "rev_proxy.df"
    container_name: "rev_proxy"
    ports:
      - "80:80"
    networks:
      - "frontend_bridge"
      - "backend_bridge"
    depends_on:
      - "frontend"
      - "backend"
    deploy:
      resources:
        limits:
          memory: "100M"
          cpus: "1"
    # for debbuging only
    #image: bitnami/nginx
    #volumes:
    #  - "./rev_proxy/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro"

  frontend:
    build:
      context: "./frontend"
      dockerfile: "frontend.df"
    container_name: "frontend"
    networks:
      - "frontend_bridge"
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "1"
    # for debbuging only
    #image: node
    #volumes:
    #  - "./frontend:/app"

  backend:
    build:
      context: "./backend"
      dockerfile: "backend.df"
    container_name: "backend"
    environment:
      - DB1_NAME
      - DB2_NAME
    networks:
      - "backend_bridge"
      - "cluster_bridge"
    depends_on:
      - "db2"
    secrets:
      - db_pass
      - db_user
    expose:
      - "4000"
    deploy:
      resources:
        limits:
          memory: "300M"
          cpus: "1"
    # for debbuging only
    #image: bitnami/node
    #volumes:
    #  - "./backend:/app"

  db1:
    image: "bitnami/cassandra:4.0.7"
    container_name: $DB1_NAME
    networks:
      - "cluster_bridge"
    environment:
      - CASSANDRA_PASSWORD_SEEDER
      - CASSANDRA_PASSWORD
      - CASSANDRA_USER
      - CASSANDRA_CLUSTER_NAME
      - CASSANDRA_SEEDS
    volumes:
      - "node1_storage:$CASSANDRA_STORAGE_PATH"
      - "$CQL_SCRIPTS_PATH:$CASSANDRA_SCRIPTS_PATH"
    expose:
      - 7000
      - 9042
    deploy:
      resources:
        limits:
          memory: 5G
          cpus: "8"

  db2:
    image: "bitnami/cassandra:4.0.7"
    container_name: $DB2_NAME
    networks:
      - "cluster_bridge"
    environment:
      - CASSANDRA_SEEDS
      - CASSANDRA_CLUSTER_NAME
    expose:
      - 7000
      - 9042
    volumes:
      - "node2_storage:$CASSANDRA_STORAGE_PATH"
    deploy:
      resources:
        limits:
          memory: 5G
          cpus: "8"

networks:
  frontend_bridge:
  backend_bridge:
  cluster_bridge:

volumes:
  node1_storage:
  node2_storage:

secrets:
  db_pass:
    file: "./secrets/db_pass.txt"
  db_user:
    file: "./secrets/db_user.txt"
