apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: brunopec/backend:v1.0.9
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: db-auth
              mountPath: /k8s/secrets
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "1000m"
              memory: "200Mi"
            requests:
              cpu: "10m"
              memory: "100Mi"

      volumes:
        - name: db-auth
          secret:
            secretName: database-auth
