apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: brunopec/backend:v1.0.9
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: db-auth
              mountPath: /k8s/secrets
      volumes:
        - name: db-auth
          secret:
            secretName: database-auth
