apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettools
spec:
  selector:
    matchLabels:
      app: nettools
  template:
    metadata:
      labels:
        app: nettools 
    spec:
      containers:
        - name: nettools
          image: travelping/nettools
          command: ["sleep"]
          args: ["10000"]
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
